### ISSUE TITLE
Unable to run the setup script

### ISSUE THREAD

**Issue by karnakar** [PredixDev/MobileExample-iOS-NativeIssuesListApp#1]
Hi,

I cloned the repo after building same app, tried to run setup script for the data, following error "no such file or directory, open '/Users/Desktop/WorkSpace/MobileExample-iOS-NativeIssuesListApp-master/setup/dist-zip/app-native-issue-viewer_1.0.zip'
    at Error (native)" is thrown.

**Comment by p0015631** [comment]
I met the same issue , and i created a dist folder , and it resolved .   Hope it can help u.

But after that i have another issue when start the app  Initial server not configured .
